name: "KiCost demo using cache"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  KiCost:
    name: Run KiCost
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto:dev

    steps:
    - name: Checkout (only last code)
      uses: actions/checkout@v3

    - name: Cache KiCost data
      id: kicost-cache
      #uses: actions/cache@v3
      uses: set-soft/cache@main
      with:
        path: ~/kicost_cache
        key: kicost_cache

    - name: Run KiBot
      env:
        ELEMENT14_KEY: ${{ secrets.ELEMENT14_KEY }}
        MOUSER_KEY: ${{ secrets.MOUSER_KEY }}
        TME_TOKEN: ${{ secrets.TME_TOKEN }}
        TME_APP_SECRET: ${{ secrets.TME_APP_SECRET }}
        NEXAR_CLIENT_ID: ${{ secrets.NEXAR_CLIENT_ID }}
        NEXAR_CLIENT_SECRET: ${{ secrets.NEXAR_CLIENT_SECRET }}
      run: |
        ##### Experimental stuff:
        # apt-get update
        # apt-get -y install --no-install-recommends  -t bullseye-backports python3-pip unzip curl python3-setuptools python3-wheel
        ## Install KiCost@master
        # curl https://codeload.github.com/hildogjr/KiCost/zip/refs/heads/master --output pp.zip
        # unzip pp.zip
        # pip3 install KiCost-master/
        ## Clean the downloaded stuff
        # rm -rf KiCost-master pp.zip
        ##### End Experimental stuff:
        mkdir KiCost
        kibot -vvvv 2> KiCost/kibot.log

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: All_Outputs
        path: KiCost
